SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[User_Role] (
		[FKIdUser]     [int] NOT NULL,
		[FKIdRole]     [int] NOT NULL,

) ON [PRIMARY]
GO
ALTER TABLE [dbo].[User_Role] SET (LOCK_ESCALATION = TABLE)
GO
